[package]
name = "StableMarket"
version = "0.0.1"
edition = "2024"

[dependencies]
Sui = { git = "https://gitee.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
stb = "0x0"
sui = "0x2"
